import { CarOffer } from './types'

export const mockCarsItems: CarOffer[] = [
    {
        id: "2602271326465",
        title: "Jeep Grand Cherokee",
        company: "Jeep",
        modelFull: "Grand Cherokee Summit Reserve",
        ez: "06/2023",
        motor: "Hybrid Benzin",
        mileage: 56149,
        rk: 61792.23,
        wbw: 59500,
        locationZip: "DE-71634",
        powerKw: 200,
        capacityCcm: 1995,
        endDate: "01.03.2026",
        endTime: "12:39",
        status: "active",
        imageUrls: [
            "/images/jeep/jeep_01.jpg",
            "/images/jeep/jeep_02.jpg",
            "/images/jeep/jeep_03.jpg",
            "/images/jeep/jeep_04.jpg",
            "/images/jeep/jeep_05.jpg",
            "/images/jeep/jeep_06.jpg",
            "/images/jeep/jeep_07.jpg",
            "/images/jeep/jeep_08.jpg",
            "/images/jeep/jeep_09.jpg",
            "/images/jeep/jeep_10.jpg",
            "/images/jeep/jeep_11.jpg",
            "/images/jeep/jeep_12.jpg",
            "/images/jeep/jeep_13.jpg",
            "/images/jeep/jeep_14.jpg",
            "/images/jeep/jeep_15.jpg",
            "/images/jeep/jeep_16.jpg",
            "/images/jeep/jeep_17.jpg",
            "/images/jeep/jeep_18.jpg",
            "/images/jeep/jeep_19.jpg",
            "/images/jeep/jeep_20.jpg",
        ],
        vin: "XXXXXXXXXXXX23994",
        gearbox: "Automatik",
        nextHu: "07/2027",
        color: "schwarz",
        distanceKm: 247,
        partsCost: 41451.99,
        laborCost: 8109.00,
        paintCost: 2345.25,
        equipment: [
            "Allradantrieb, automatisches Getriebe, Dachreling, elektrische Fensterheber vorne und hinten, Lederausstattung, Leichtmetallfelgen, Nebelscheinwerfer, Einparkhilfe, Panoramaschiebedach, Sitzheizung vorne, Stoßfänger lackiert.",
            "Serienausstattung:",
            "AB MODELL 2023 SCHEIBEN DUNKEL GET F-HEBER L/R IMPULSG FRONTSCHEIBE HEIZBAR KOLLISIONSWARNSYSTEM A-SPIEGEL ELEKTRISCH A-SPIEG ASPHAERISCH I-SPIEG AUT ABBLENDB RADIO MIT BILD 10.1 19 LAUTSPRECHER AUDIOSYSTEM DIGITAL PROJEKTORSCHEINW LED NEBELSCHEINWERFER TUERGRIFFE BELEUCHT LEUCHTW-REG AUTOMAT NEBELSCHLUSSLEUCHTE SITZHEIZUNG H LORDOSENST SITZ V SITZE VORN BELUEFTET SONNENSCHUTZROLLO REGENSENSOR GRILL TEXTUR C FAHRKAMERA 360 GRAD OFFROAD KAMERA HECKTUEROEFFNUNG ELE ZIERL RADHAUS LACK ZIERL SEITL LACKIERT SHUTTER-SYSTEM AUSPUFFBLENDE CHROM EINPARKH V/H/SEITL ZIERLEISTE TEXTUR C 1994CCM 280KW MOTORKUEHLUNG 8-GANG GETRIEBE AUT SERVOLENKUNG ELEKTR FAHRWERK TUNED LENKSP REGUL ELEKTR DIFF-SPERRE ELEKTR FAHRWERK QUADRA-LIFT DIFFERENTIAL 230MM NACHT VISION KAMERA HEAD-UP DISPLAY 275/45 R 21 ..V * WINTERREIFEN FELGE 9 J X 21 ALU QUADRA-TRAC II FUSSGAENGERSCHUTZ DACHRELING PANORAMADACH KURZVERSION STOSSF V U LACKIERT SCHUTZL MIT EINSATZ"
        ],
        reportText: `Laufleistung: abgelesen 56149
Zustand: normal
Ein starker Frontanstoß mit Beschädigungen im Unterbodenbereich, der Achskomponenten vorne rechts und links sowie hinten rechts und hinten links, der Lenkung, der Auspuffanlage und weiterer Anbauteile.
Nicht reparierte Vorschäden:
Gebrauchsspuren.
Bemerkungen:
Das Fahrzeug war bei der Besichtigung witterungsbedingt verschmutzt.
Einsteller: GAUL GmbH & Co. KG`,
        calculationText: `Kalkulation aus dem System Audatex. Gesamt Rep.-Kosten MIT MWST: 61 792.23 €.`,
        kalkulationDetails: [
            { position: 1, name: "FAHRZEUG KPL VERMESSEN UND EINSTELLEN", price: 503.50, type: "L" },
            { position: 2, name: "STOSSFAENGER V KPL ERSETZEN", price: 397.50, type: "L" },
            { position: 3, name: "STOSSFAENGER H U ERSETZEN", price: 318.00, type: "L" },
            { position: 4, name: "KRAFTSTOFFBEHAELTER AUS-/EINBAUEN", price: 583.00, type: "L" },
            { position: 5, name: "SERVOLENKUNG A-E", price: 1166.00, type: "L" },
            { position: 6, name: "ACHSTRAEGER V AUS-/EINBAUEN", price: 927.50, type: "L" },
            { position: 7, name: "STOSSFAENGER V O NEUTEILLACK", price: 212.00, type: "NL" },
            { position: 8, name: "STOSSFAENGER V O (68575117AB)", price: 776.34, type: "E" },
            { position: 9, name: "STOSSFAENGER V U (68575120AA)", price: 436.81, type: "E" },
            { position: 10, name: "RADLAUFLEISTE V L (6UX15TZZAC)", price: 453.22, type: "E" },
            { position: 11, name: "RADLAUFLEISTE V R (6UX14TZZAC)", price: 464.54, type: "E" },
            { position: 12, name: "KRAFTSTOFFBEHAELTER (68551396AA)", price: 2186.17, type: "E" },
            { position: 13, name: "TRAGRAHMEN V (68438645AG)", price: 2846.47, type: "E" },
            { position: 14, name: "ACHSSCHENKEL V L (68375451AC)", price: 943.36, type: "E" },
            { position: 15, name: "ACHSSCHENKEL V R (68375450AC)", price: 966.94, type: "E" },
            { position: 16, name: "SERVOLENKGETRIEBE (68628263AC)", price: 3917.60, type: "E" },
            { position: 17, name: "AUSPUFFTOPF H (68615247AA)", price: 2688.00, type: "E" },
            { position: 18, name: "HINTERACHSE MIT DIFF (68340259AC)", price: 5749.85, type: "E" },
            { position: 19, name: "RAHMEN H (68630413AB)", price: 1389.43, type: "E" }
        ]
    },
    {
        id: "2602231411840",
        title: "Suzuki Swift",
        company: "Suzuki",
        modelFull: "Swift, Club",
        ez: "04/2011",
        motor: "Otto",
        mileage: 191916,
        rk: 3455,
        wbw: 3749,
        locationZip: "DE 97...",
        powerKw: 69,
        capacityCcm: 1242,
        endDate: "24.02.2026",
        endTime: "14:09",
        status: "bid_placed",
        currentBid: 550,
        imageUrls: [
            "https://images.unsplash.com/photo-1542282088-fe8426682b8f?q=80&w=800",
            "https://images.unsplash.com/photo-1542282088-000000000000?q=80&w=800"
        ],
        vin: "XXXXXXXXXXXXXX82811",
        gearbox: "Manuell",
        nextHu: "01/2027",
        color: "schwarz",
        distanceKm: 420,
        partsCost: 1200,
        laborCost: 800,
        paintCost: 1455,
        equipment: ["Klimaanlage", "Radio CD", "Servolenkung"],
        reportText: "Kein Detailbericht verfügbar.",
        calculationText: "Kalkulation liegt vor."
    },
    {
        id: "2602231411841",
        title: "Mercedes-Benz C-Klasse",
        company: "Mercedes-Benz",
        modelFull: "C-Klasse, C 220 (BlueTEC) d T 7G-TRONIC Avantgarde",
        ez: "09/2014",
        motor: "Diesel",
        mileage: 155188,
        rk: 8513,
        wbw: 16000,
        locationZip: "DE 13...",
        powerKw: 125,
        capacityCcm: 2143,
        endDate: "24.02.2026",
        endTime: "14:10",
        status: "active",
        imageUrls: [
            "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800"
        ],
        vin: "XXXXXXXXXXXXXX44412",
        gearbox: "Automatik",
        nextHu: "11/2025",
        color: "weiß",
        distanceKm: 150,
        partsCost: 4500,
        laborCost: 2000,
        paintCost: 2013,
        equipment: ["Navigationssystem", "LED Scheinwerfer", "Sitzheizung", "Einparkhilfe"],
        reportText: "Frontschaden, Kühler undicht. Airbags ausgelöst.",
        calculationText: "Reparaturkosten übersteigen möglicherweise den Restwert. Details siehe Kalkulationsdokument."
    }
];
